# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 713839855a7009558e19393b122b38ee3408a6151056c12ce27563b7fbdb453e2e43f0f38615f70e38f0149fb38ba18a946fadd804d01513e624ebc741250d46

test:
  secret_key_base: d376e47cf150ed2fe22ef61f0a7b10947e27a2b85d6f00649667a858de4f00d8b5bb5ae1668712fbc5ed40c0d4c2e6a7b9b5fc7ae0ee99506f0ebf049589e235

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
